### ISSUE TITLE
Sorry in advance to contact you here 

### ISSUE THREAD

**Issue by CandySign** [apsun/sc2mp3#7]
Hi,

I created an account on Github only to ask you if you will continue supporting your project GoogleImageShell? I've been using it for years and it only stopped working this month returning this (https://i.imgur.com/PPxrnJb.png), I only wish you or someone would fix it, please if you know of any similar tools do tell me.

Thank you, and sorry again for contacting you through another project...

**Comment by apsun** [comment]
No, sorry, I no longer use Windows and do not have the time to maintain that project. Thanks for your understanding.
